DELETE FROM code_category WHERE created_by = 'none';
INSERT INTO code_category(category_key, category_name, created_by, created_at) VALUES
('GNR0001', '성별', 'none', NOW()),
('GNR0002', '시군구', 'none', NOW()),
('GNR0003', '유무구분', 'none', NOW());

DELETE FROM code WHERE created_by = 'none';
INSERT INTO code(code_category_id, code_key, code_value, code_alias, display_order, is_invalid, created_by, created_at) VALUES
((SELECT code_category_id FROM code_category WHERE category_key = 'GNR0001' AND deleted_at IS NULL), '01', '남', 'male', 1, 0, 'none', NOW()),
((SELECT code_category_id FROM code_category WHERE category_key = 'GNR0001' AND deleted_at IS NULL), '02', '여', 'female', 2, 0, 'none', NOW()),
((SELECT code_category_id FROM code_category WHERE category_key = 'GNR0002' AND deleted_at IS NULL), '01', '서울특별시', NULL, 1, 0, 'none', NOW()),
((SELECT code_category_id FROM code_category WHERE category_key = 'GNR0002' AND deleted_at IS NULL), '02', '부산광역시', NULL, 2, 0, 'none', NOW()),
((SELECT code_category_id FROM code_category WHERE category_key = 'GNR0002' AND deleted_at IS NULL), '03', '인천광역시', NULL, 3, 0, 'none', NOW()),
((SELECT code_category_id FROM code_category WHERE category_key = 'GNR0002' AND deleted_at IS NULL), '04', '대구광역시', NULL, 4, 0, 'none', NOW()),
((SELECT code_category_id FROM code_category WHERE category_key = 'GNR0002' AND deleted_at IS NULL), '05', '대전광역시', NULL, 5, 0, 'none', NOW()),
((SELECT code_category_id FROM code_category WHERE category_key = 'GNR0002' AND deleted_at IS NULL), '06', '광주광역시', NULL, 6, 0, 'none', NOW()),
((SELECT code_category_id FROM code_category WHERE category_key = 'GNR0002' AND deleted_at IS NULL), '07', '경기도 수원시', NULL, 7, 0, 'none', NOW()),
((SELECT code_category_id FROM code_category WHERE category_key = 'GNR0002' AND deleted_at IS NULL), '08', '울산광역시', NULL, 8, 0, 'none', NOW()),
((SELECT code_category_id FROM code_category WHERE category_key = 'GNR0002' AND deleted_at IS NULL), '09', '경기도 고양시', NULL, 9, 0, 'none', NOW()),
((SELECT code_category_id FROM code_category WHERE category_key = 'GNR0002' AND deleted_at IS NULL), '10', '경기도 용인시', NULL, 10, 0, 'none', NOW()),
((SELECT code_category_id FROM code_category WHERE category_key = 'GNR0002' AND deleted_at IS NULL), '11', '경상남도 창원시', NULL, 11, 0, 'none', NOW()),
((SELECT code_category_id FROM code_category WHERE category_key = 'GNR0002' AND deleted_at IS NULL), '12', '경기도 성남시', NULL, 12, 0, 'none', NOW()),
((SELECT code_category_id FROM code_category WHERE category_key = 'GNR0002' AND deleted_at IS NULL), '13', '충청북도 청주시', NULL, 13, 0, 'none', NOW()),
((SELECT code_category_id FROM code_category WHERE category_key = 'GNR0002' AND deleted_at IS NULL), '14', '경기도 부천시', NULL, 14, 0, 'none', NOW()),
((SELECT code_category_id FROM code_category WHERE category_key = 'GNR0002' AND deleted_at IS NULL), '15', '경기도 화성시', NULL, 15, 0, 'none', NOW()),
((SELECT code_category_id FROM code_category WHERE category_key = 'GNR0002' AND deleted_at IS NULL), '16', '경기도 남양주시', NULL, 16, 0, 'none', NOW()),
((SELECT code_category_id FROM code_category WHERE category_key = 'GNR0002' AND deleted_at IS NULL), '17', '전라북도 전주시', NULL, 17, 0, 'none', NOW()),
((SELECT code_category_id FROM code_category WHERE category_key = 'GNR0002' AND deleted_at IS NULL), '18', '충청남도 천안시', NULL, 18, 0, 'none', NOW()),
((SELECT code_category_id FROM code_category WHERE category_key = 'GNR0002' AND deleted_at IS NULL), '19', '경기도 안산시', NULL, 19, 0, 'none', NOW()),
((SELECT code_category_id FROM code_category WHERE category_key = 'GNR0002' AND deleted_at IS NULL), '20', '경기도 안양시', NULL, 20, 0, 'none', NOW()),
((SELECT code_category_id FROM code_category WHERE category_key = 'GNR0002' AND deleted_at IS NULL), '21', '경상남도 김해시', NULL, 21, 0, 'none', NOW()),
((SELECT code_category_id FROM code_category WHERE category_key = 'GNR0002' AND deleted_at IS NULL), '22', '경기도 평택시', NULL, 22, 0, 'none', NOW()),
((SELECT code_category_id FROM code_category WHERE category_key = 'GNR0002' AND deleted_at IS NULL), '23', '경상북도 포항시', NULL, 23, 0, 'none', NOW()),
((SELECT code_category_id FROM code_category WHERE category_key = 'GNR0002' AND deleted_at IS NULL), '24', '제주특별자치도 제주시', NULL, 24, 0, 'none', NOW()),
((SELECT code_category_id FROM code_category WHERE category_key = 'GNR0002' AND deleted_at IS NULL), '25', '경기도 시흥시', NULL, 25, 0, 'none', NOW()),
((SELECT code_category_id FROM code_category WHERE category_key = 'GNR0002' AND deleted_at IS NULL), '26', '경기도 파주시', NULL, 26, 0, 'none', NOW()),
((SELECT code_category_id FROM code_category WHERE category_key = 'GNR0002' AND deleted_at IS NULL), '27', '경기도 의정부시', NULL, 27, 0, 'none', NOW()),
((SELECT code_category_id FROM code_category WHERE category_key = 'GNR0002' AND deleted_at IS NULL), '28', '경기도 김포시', NULL, 28, 0, 'none', NOW()),
((SELECT code_category_id FROM code_category WHERE category_key = 'GNR0002' AND deleted_at IS NULL), '29', '경상북도 구미시', NULL, 29, 0, 'none', NOW()),
((SELECT code_category_id FROM code_category WHERE category_key = 'GNR0002' AND deleted_at IS NULL), '30', '경기도 광주시', NULL, 30, 0, 'none', NOW()),
((SELECT code_category_id FROM code_category WHERE category_key = 'GNR0002' AND deleted_at IS NULL), '31', '경상남도 양산시', NULL, 31, 0, 'none', NOW()),
((SELECT code_category_id FROM code_category WHERE category_key = 'GNR0002' AND deleted_at IS NULL), '32', '강원도 원주시', NULL, 32, 0, 'none', NOW()),
((SELECT code_category_id FROM code_category WHERE category_key = 'GNR0002' AND deleted_at IS NULL), '33', '경상남도 양산시', NULL, 33, 0, 'none', NOW()),
((SELECT code_category_id FROM code_category WHERE category_key = 'GNR0002' AND deleted_at IS NULL), '34', '경기도 광주시', NULL, 34, 0, 'none', NOW()),
((SELECT code_category_id FROM code_category WHERE category_key = 'GNR0002' AND deleted_at IS NULL), '34', '강원도 원주시', NULL, 35, 0, 'none', NOW()),
((SELECT code_category_id FROM code_category WHERE category_key = 'GNR0002' AND deleted_at IS NULL), '36', '경상남도 진주시', NULL, 36, 0, 'none', NOW()),
((SELECT code_category_id FROM code_category WHERE category_key = 'GNR0002' AND deleted_at IS NULL), '37', '세종특별자치시', NULL, 37, 0, 'none', NOW()),
((SELECT code_category_id FROM code_category WHERE category_key = 'GNR0002' AND deleted_at IS NULL), '38', '경기도 광명시', NULL, 38, 0, 'none', NOW()),
((SELECT code_category_id FROM code_category WHERE category_key = 'GNR0002' AND deleted_at IS NULL), '39', '충청남도 아산시', NULL, 39, 0, 'none', NOW()),
((SELECT code_category_id FROM code_category WHERE category_key = 'GNR0002' AND deleted_at IS NULL), '40', '전라북도 익산시', NULL, 40, 0, 'none', NOW()),
((SELECT code_category_id FROM code_category WHERE category_key = 'GNR0002' AND deleted_at IS NULL), '41', '강원도 춘천시', NULL, 41, 0, 'none', NOW()),
((SELECT code_category_id FROM code_category WHERE category_key = 'GNR0002' AND deleted_at IS NULL), '42', '경상북도 경산시', NULL, 42, 0, 'none', NOW()),
((SELECT code_category_id FROM code_category WHERE category_key = 'GNR0002' AND deleted_at IS NULL), '43', '경기도 군포시', NULL, 43, 0, 'none', NOW()),
((SELECT code_category_id FROM code_category WHERE category_key = 'GNR0002' AND deleted_at IS NULL), '44', '경기도 하남시', NULL, 44, 0, 'none', NOW()),
((SELECT code_category_id FROM code_category WHERE category_key = 'GNR0002' AND deleted_at IS NULL), '45', '전라남도 여수시', NULL, 45, 0, 'none', NOW()),
((SELECT code_category_id FROM code_category WHERE category_key = 'GNR0002' AND deleted_at IS NULL), '46', '경상북도 경주시', NULL, 46, 0, 'none', NOW()),
((SELECT code_category_id FROM code_category WHERE category_key = 'GNR0002' AND deleted_at IS NULL), '47', '경기도 이천시', NULL, 47, 0, 'none', NOW()),
((SELECT code_category_id FROM code_category WHERE category_key = 'GNR0003' AND deleted_at IS NULL), '01', '무', NULL, 1, 0, 'none', NOW()),
((SELECT code_category_id FROM code_category WHERE category_key = 'GNR0003' AND deleted_at IS NULL), '02', '유', NULL, 2, 0, 'none', NOW());
